### ISSUE TITLE
Mark constructors/assignment/swap noexcept where possible

### ISSUE THREAD

**Issue by Lastique** [boostorg/interprocess#122]
Please mark functions `noexcept` where possible for the types provided by Boost.Interprocess. In particular, I'm interested in types `shared_memory_object` and `mapped_region`, but this is probably not limited to those.

The functions that have immediate benefit from being marked are:
- Default constructors.
- Move constructors and assignment.
- Copy constructors and assignment, where possible.
- `swap`.

The important effects of this markup includes:
- More efficient implementation of standard containers and algorithms.
- Implicitly defined constructors and operators of user's types that have Boost.Interprocess types in members or base classes become `noexcept`.

**Comment by igaztanaga** [comment]
Many thanks for the report!
