### ISSUE TITLE
 infinite loop in managed_open_or_create_impl.hpp

### ISSUE THREAD

**Issue by mmhatami** [boostorg/interprocess#128]
when create a boost::interprocess::managed_shared_memory, if the process killed exactly before set atomic_write32(patomic_word, InitializedSegment) in managed_open_or_create_impl.hpp ,

`detail::atomic_write32(patomic_word, InitializedSegment);`

another process will be caught in an infinite loop in managed_open_or_create_impl.hpp

     boost::uint32_t *patomic_word = static_cast<boost::uint32_t*>(region.get_address());
     boost::uint32_t value = detail::atomic_read32(patomic_word);

     while(value == InitializingSegment || value == UninitializedSegment){
        detail::thread_yield();
        value = detail::atomic_read32(patomic_word);
     }

**Comment by igaztanaga** [comment]
Thanks for the report. The implementation will add deadlock detection code with configurable macros BOOST_INTERPROCESS_MANAGED_OPEN_OR_CREATE_INITIALIZE_MAX_TRIES/BOOST_INTERPROCESS_MANAGED_OPEN_OR_CREATE_INITIALIZE_TIMEOUT_SEC to handle those situations, as there is no reliable way to detect the other process creating the resource is dead or not.
