### ISSUE TITLE
infinite loop in managed_open_or_create_impl.hpp if filesize is 0

### ISSUE THREAD

**Issue by cmorty** [boostorg/interprocess#130]
Calling `managed_mapped_file(bip::open_only,filename)` on a file with size 0 results in a in infinite loop.

```C++
            offset_t filesize = 0;
            spin_wait swait;
            while(filesize == 0){
               if(!get_file_size(file_handle_from_mapping_handle(dev.get_mapping_handle()), filesize)){
                  error_info err = system_error_code();
                  throw interprocess_exception(err);
               }
               swait.yield();
            }
```

**Comment by Master-Faraz** [comment]
Initially the filesize is zero and the size is not changed in while loop. So it is getting in infinite while loop. Change the value of filesize inside the while loop to get rid of this error

**Comment by igaztanaga** [comment]
A correctly created managed file can't have zero size. Code is waiting the create process to initialize the managed file (in case of error, file will be truncated to size 1). Which is your use case?

**Comment by igaztanaga** [comment]
Thanks for the report. The implementation will add deadlock detection code with configurable macros BOOST_INTERPROCESS_MANAGED_OPEN_OR_CREATE_INITIALIZE_MAX_TRIES/BOOST_INTERPROCESS_MANAGED_OPEN_OR_CREATE_INITIALIZE_TIMEOUT_SEC to handle those situations, as there is no reliable way to detect the other process creating the resource is dead or not.
