### ISSUE TITLE
Support BOOST_NO_ANSI_APIS

### ISSUE THREAD

**Issue by zhaohuaxishi** [boostorg/interprocess#141]
```
#define BOOST_NO_ANSI_APIS 1
#include "boost/interprocess/sync/file_lock.hpp"
int main() {}
```
Fails to compile

See also https://github.com/boostorg/process/issues/26

**Comment by igaztanaga** [comment]
¿Why should we support this in Interprocess? ¿Why is useful?

**Comment by zhaohuaxishi** [comment]
> ¿Why should we support this in Interprocess? ¿Why is useful?

https://www.boost.org/doc/libs/1_75_0/libs/winapi/doc/html/winapi/config.html

> 

BOOST_NO_ANSI_APIS | This macro is defined by Boost.Config on platforms that do not support narrow-character versions of some APIs. Boost.WinAPI will not declare narrow-character APIs when this macro is defined.
-- | --
