### ISSUE TITLE
Can't link boost::interprocess library in Ubuntu. Lib non-existent?

### ISSUE THREAD

**Issue by piffy** [boostorg/interprocess#148]
I am moving my first steps with Boost. I am working on  the example program that uses boost::interprocess::shared memory , as shown in https://www.boost.org/doc/libs/1_49_0/doc/html/interprocess/sharedmemorybetweenprocesses.html

Though the program compiles OK, I'm unable to link it.  I tried several CLI commands, the most promising being 
```
g++ boostshm.cpp -lboost_interprocess -ltr
```
It states that it can't find lboost_interprocess. This is also confirmed by listing boost libraries in /usr/lib.

Note: I am using Ubuntu 20.04.  I installed Boost with `sudo apt install libboost-all-dev`, and other Boost programs compile and link just fine.

**Comment by niXman** [comment]
as far as I know this is a header-only library.

**Comment by piffy** [comment]
You are right. I managed by linking the appropriate libraries.
