### ISSUE TITLE
Handle EINTR in shared_memory_object

### ISSUE THREAD

**Issue by Lastique** [boostorg/interprocess#152]
As documented, [`shm_open`](https://pubs.opengroup.org/onlinepubs/007904875/functions/shm_open.html) may return `EINTR` if interrupted by a signal. This error code is not specially handled in `shared_memory_object::priv_open_or_create` and will result in an exception being thrown. It would be better if the `shm_open` call was attempted again internally by `shared_memory_object` without an exception.

**Comment by igaztanaga** [comment]
Many thanks for the report.
