### ISSUE TITLE
Set sticky bit on shared interprocess folder

### ISSUE THREAD

**Issue by MarcusAckermann** [boostorg/interprocess#157]
It is considered as a CVE to have a world-writable directory without the sticky bit set on Unix filesystems.

The shared interprocess folder (/tmp/boost_interprocess) which is created by `create_shared_dir_and_clean_old` in `boost/interprocess/detail/shared_dir_helpers.hpp` explicitly gets the permissions `0777` which makes it a world-writable directory without the sticky bit.

This folder should be created with `1777` instead to have the sticky bit set. The `/tmp` folder has the sticky bit set.

**Comment by igaztanaga** [comment]
Many thanks for the report!
