### ISSUE TITLE
Disabling runtime type identification feature cause an error during compilation

### ISSUE THREAD

**Issue by cngzhnp** [boostorg/interprocess#164]
Boost Version : 1.78
GCC Version : 11.2.0

When we try to compile `Boost::Interprocess` component with disabling **RTTI** (via `-fno-rtti` option with GCC) cause a compilation error due to standard `typeid `implementation.

Here is the simple build command and result with `-fno-rtti ` option:

`g++ -Wall -fno-rtti detail/in_place_interface.hpp -I ../../ -o wout_rtti`

```
detail/in_place_interface.hpp:19:11: warning: #pragma once in main file
   19 | #  pragma once
      |           ^~~~
detail/in_place_interface.hpp: In constructor ‘boost::interprocess::ipcdetail::placement_destroy<T>::placement_destroy()’:
detail/in_place_interface.hpp:56:15: error: cannot use ‘typeid’ with ‘-fno-rtti’
   56 |       typeid(T).name())
      |               ^
```

**Comment by igaztanaga** [comment]
Reviewing old bugs.

Unfortunately Boost.Interprocess is not designed to build without RTTI or exceptions and there are no plans to support those systems as environments with shared memory or memory mapped files are supposedly complex enough to afford them.
