### ISSUE TITLE
Bad error handling in shared_memory_object::truncate

### ISSUE THREAD

**Issue by andrust** [boostorg/interprocess#166]
https://github.com/boostorg/interprocess/blob/6982a86d97edfffb0f69230c3ca5f7ed9a1a1200/include/boost/interprocess/shared_memory_object.hpp#L466

According to posix_fallocate man page: _posix_fallocate() returns zero on success, or an error number on failure.  Note that errno is not set._

`ret` should be used instead of `system_error_code()` when throwing exception.

**Comment by igaztanaga** [comment]
Thanks for the report, I'll apply the fix you propose.

**Comment by andrust** [comment]
Thanks for fixing!
