### ISSUE TITLE
check_sanity() scoped mutex locked after assertion

### ISSUE THREAD

**Issue by lioriz** [boostorg/interprocess#177]
In [check_sanity()](https://github.com/boostorg/interprocess/blob/develop/include/boost/interprocess/mem_algo/rbtree_best_fit.hpp#L636) function,
In the scenario where multiple processes share the same ```shared memory```, if the ```shared memory``` is corrupted for some reason then when one of the processes calls ```check_sanity()``` the [scoped mutex](https://github.com/boostorg/interprocess/blob/develop/include/boost/interprocess/mem_algo/rbtree_best_fit.hpp#L639) in the function locks but the process [crashes with assertion](https://github.com/boostorg/interprocess/blob/develop/include/boost/interprocess/mem_algo/rbtree_best_fit.hpp#L648) without unlocking the mutex, causing any other process that will call ```check_sanity()``` to be stuck on the locked ```scoped mutex```.

If there is a ```mutex``` in a ```shared memory``` object it must be unlocked before ```assertion```, ```exception```, or ```return```.
I would expect the ```check_sanity()``` function to return ```false``` in the case of corrupted memory instead of ```assert```.

**Comment by igaztanaga** [comment]
Many thanks for the PR!

**Comment by lioriz** [comment]
> Many thanks for the PR!

My pleasure.
