### ISSUE TITLE
Feature Request: Add support for monotonic/steady_clock timeouts

### ISSUE THREAD

**Issue by davidsj2** [boostorg/interprocess#182]
Current synchronization objects use absolute time for timeouts, which are susceptible to unexpected behavior in the face of clock adjustments.  It would be nice to support relative timeouts using monotonic clock in interprocess condition variables and mutexes like is supported in POSIX and the C++ standard lib (generally), respectively.

**Comment by igaztanaga** [comment]
From Version 1.78 already supports relative timeouts (e.g. try_lock_for):

https://www.boost.org/doc/libs/1_79_0/doc/html/boost/interprocess/interprocess_mutex.html#idm30792-bb

Isn't that what you are requesting?

**Comment by igaztanaga** [comment]
Closing the issue as completed.
