### ISSUE TITLE
Local memory only implementation

### ISSUE THREAD

**Issue by alex4747-pub** [boostorg/interprocess#203]
It will be nice to provide a local memory-only implementation:  the same API for data stored in a bloc of local memory.

It will be really useful for unit tests.

It will be also useful when we load existing data into the local memory from some store, modify data in memory, and then save modified data in the store.

**Comment by alex4747-pub** [comment]
Mistaken: it seems that this feature is already supported

**Comment by pliniofpa** [comment]
Please close this issue.
