### ISSUE TITLE
interprocess_condition::timed_wait() requires time as universal_time, not local_time

### ISSUE THREAD

**Issue by Tails86** [boostorg/interprocess#237]
Boost version: 1.86.0
OS: Linux, Ubuntu 22.04

I'm used to using ` boost::posix_time::microsec_clock::local_time()` or `std::chrono::steady_clock::now()` as my time base for most boost timed wait functionality. However, it seems that `interprocess_condition::timed_wait()` returns false immediately for me when I have a time 1 second in the future (I am in UTC-7 time zone). Things start to work fine if I either adjust my system time to UTC+0 or update the code to instead use `boost::posix_time::microsec_clock::universal_time()` as my time base.

**Comment by Tails86** [comment]
If this is instead a misunderstanding on my end, I would like to see the documentation updated to clarify this. 

The one area I have played around with where the type of clock used didn't seem to matter was with `boost::asio::io_service::run_until()` where I use an offset from `std::chrono::steady_clock::now()`. Since this is all a part of boost, I assumed I could just reference this code for interprocess code.

**Comment by igaztanaga** [comment]
This is mentioned in the documentation:

https://www.boost.org/doc/libs/1_86_0/doc/html/interprocess/synchronization_mechanisms.html#interprocess.synchronization_mechanisms.mutexes.mutexes_scoped_lock

"Boost.Interprocess timed synchronization operations support several timepoints: boost::posix_time::ptime absolute UTC time points, boost::chrono and std::chrono timepoints"

Maybe it's not visible enough and this should be placed in a general section.

**Comment by Tails86** [comment]
The more I look around, the more it seems to me like this is a well-known thing that I just missed because I was mainly looking at the class definition documentation itself. I wouldn't feel upset if this is deemed as something that is documented enough based on the links provided.

**Comment by igaztanaga** [comment]
Thanks for the feedback, closing the issue.
