### ISSUE TITLE
Data race in boost::interprocess::rbtree_best_fit 

### ISSUE THREAD

**Issue by ostash** [boostorg/interprocess#41]
Ther is a race on bit-field (https://github.com/google/sanitizers/wiki/ThreadSanitizerPopularDataRaces#race-on-bit-field).

If we take a look on ```boost::interprocess::rbtree_best_fit::SizeHolder```:

```c++
struct SizeHolder
{
   //!This block's memory size (including block_ctrl
   //!header) in Alignment units
   size_type m_prev_size :  sizeof(size_type)*CHAR_BIT;
   size_type m_size      :  sizeof(size_type)*CHAR_BIT - 2;
   size_type m_prev_allocated :  1;
   size_type m_allocated :  1;
};
```
non-synchronized access to ```m_prev_size``` and ```m_size``` is a race.
From what I understand from reading source, it is allowed to write ```UsableByPreviousChunk``` bytes past allocated block, or to ```m_prev_size``` of next block. But during allocation reads and writes to ```m_size``` are performed.

**Comment by ostash** [comment]
Simplest fix I can think of is to remove ```m_prev_size``` from bit-field:

```c++
struct SizeHolder
{
   //!This block's memory size (including block_ctrl
   //!header) in Alignment units
   size_type m_prev_size;
   size_type m_size      :  sizeof(size_type)*CHAR_BIT - 2;
   size_type m_prev_allocated :  1;
   size_type m_allocated :  1;
};
```

**Comment by igaztanaga** [comment]
Many thanks for your detailed report and fix. I tried to find the issue but could not imagine the bitfiled would be the cause. I considered m_prev_size as a separate memory location, but maybe it's incorrect and it's also better expressed removing the bit field part. thanks again!

**Comment by ostash** [comment]
Thanks for confirming and closing this!
