### ISSUE TITLE
message_queue requires prealocation of largest possible message size

### ISSUE THREAD

**Issue by feldi12** [boostorg/interprocess#44]
Hi!
In current implementation message_queue checks supplied buffer size against maximum possible message size, not against the current message size.
Moving check to place, where size of next object is already known would allow user to increase the allocated size only when needed. This would help limit memory allocation in case of queue sending messages of very different sizes.

**Comment by igaztanaga** [comment]
message_queue is modelled after POSIX message queues, where configuration parameters are:

long    mq_maxmsg   maximum number of messages
long    mq_msgsize  maximum message size

According to this POSIX model (http://pubs.opengroup.org/onlinepubs/009695399/functions/mq_send.html):

_"The value of msg_len shall be less than or equal to the mq_msgsize attribute of the message queue, or mq_send() shall fail."_

Many users depend on this design so it's not feasible to change it. Anyway, many thanks for the report.
