### ISSUE TITLE
fill_system_message() ignores an error returned by winapi::format_message()

### ISSUE THREAD

**Issue by k15tfu** [boostorg/interprocess#54]
In file `boost\interprocess\errors.hpp` the function `fill_system_message()` invokes `winapi::format_message()` but then doesn't check its return value and calls `string::operator+=` with `lpMsgBuf=nullptr`.  Obviously it leads to access violation.

**Comment by igaztanaga** [comment]
Thanks for the report. Using a fixed error string in case FormatMessage fails. Fixed in:

https://github.com/boostorg/interprocess/commit/1baf757d9f7b22ffdac8169faebc7b01efb57bf0
