### ISSUE TITLE
clang supported?

### ISSUE THREAD

**Issue by cryptocode** [boostorg/interprocess#55]
clang (macos/linux) is not listed as a tested compiler, but is the level of support known? Any known issues? Thanks for any input.

**Comment by igaztanaga** [comment]
It's tested on the regression tests and seems to work. See:

https://www.boost.org/development/tests/master/developer/interprocess.html

Clang is being tested on Linux, FreeBsd and Mac.

**Comment by cryptocode** [comment]
Thanks - the docs over supported compilers doesn't mention clang, so this is good to know! I've been have some issues with clang on macOS, but I may have been running into one of the bugs listed here:https://svn.boost.org/trac10/query?status=!closed&component=interprocess&desc=1&order=id  

Are these being worked on, or is the list outdated? Most of the problems seems to be related to deadlocks if a participating processes crashes (using named segments and condition variables).
