### ISSUE TITLE
named_mutex  posix should change semaphore to robust pthread_mutex

### ISSUE THREAD

**Issue by 363568233** [boostorg/interprocess#74]
current default implementation  use BOOST_INTERPROCESS_FORCE_GENERIC_EMULATION macro,
#include <boost/interprocess/sync/shm/named_mutex.hpp> may deadlock when ower dead
#include <boost/interprocess/sync/posix/named_mutex.hpp> is  the posix semaphore, it may also deadlock when ower dead.
why not change the named_mutx.hpp to mutex.hpp? using robust pthread_mutex
I see interprocess_mutex have been robust

**Comment by igaztanaga** [comment]
pthread mutexes are anonymous resources, not named ones. Recent commits have activated robust mutexes in interprocess_mutex and interprocess_recursive_mutex in platforms that support it. Using named semaphores for named mutexes is also used in other runtimes like APR (Apache Portable Runtime) so no plans to change this in Interprocess.
