### ISSUE TITLE
warning: Implicit conversion loses integer precision

### ISSUE THREAD

**Issue by davecotter** [boostorg/interprocess#85]
boost_1_69_0/boost/interprocess/streams/bufferstream.hpp:241:25: Implicit conversion loses integer precision: 'boost::interprocess::basic_bufferbuf<char, std::__1::char_traits<char> >::off_type' (aka 'long long') to 'int'

**Comment by igaztanaga** [comment]
Many thanks for the report!

**Comment by igaztanaga** [comment]
Many thanks for the report!
