### ISSUE TITLE
1.71. Conflict declarations

### ISSUE THREAD

**Issue by heretic13** [boostorg/interprocess#95]
OS: Windows 10 x64
Visual studio 2019 (16.3.1)
Windows SDK: 10.0.18362.0
boost 1.71

Sample program:

`
#define _WIN32_WINNT 0x0601

#include <Windows.h>
#include <boost/interprocess/sync/windows/winapi_mutex_wrapper.hpp>

int main()
{
	return 0;
}
`

74 errors during compilation!
[result.txt](https://github.com/boostorg/interprocess/files/3656678/result.txt)

**Comment by beppemarazzi** [comment]
read this: https://www.boost.org/doc/libs/1_71_0/doc/html/interprocess/acknowledgements_notes.html#interprocess.acknowledgements_notes.notes_windows.boost_use_windows_h

so you have to add `#define BOOST_USE_WINDOWS_H` before any `#include<boost/...`

**Comment by heretic13** [comment]
Thanks. It's working
